//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2BData
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemnew
    {
        public int ID { get; set; }
        public Nullable<long> numiid { get; set; }
        public string title { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<int> brandId { get; set; }
        public Nullable<int> postageID { get; set; }
        public string prostatus { get; set; }
        public string outerid { get; set; }
        public string barCode { get; set; }
        public string wareLocation { get; set; }
        public string adWords { get; set; }
        public Nullable<decimal> weight { get; set; }
        public string periodDate { get; set; }
        public string props { get; set; }
        public string logo { get; set; }
        public Nullable<decimal> jdPrice { get; set; }
        public Nullable<decimal> poPrice { get; set; }
        public string mobileDesc { get; set; }
        public string introduction { get; set; }
        public Nullable<int> iscrossPro { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
        public Nullable<System.DateTime> modifiedtime { get; set; }
        public string creater { get; set; }
        public string modified { get; set; }
        public string partermodel { get; set; }
        public Nullable<decimal> price130 { get; set; }
        public Nullable<decimal> price105 { get; set; }
        public Nullable<int> HDID { get; set; }
        public Nullable<decimal> coefficient { get; set; }
    }
}
