//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2BData
{
    using System;
    using System.Collections.Generic;
    
    public partial class payOrder
    {
        public long tid { get; set; }
        public string out_trade_no { get; set; }
        public Nullable<System.DateTime> time_start { get; set; }
        public Nullable<System.DateTime> time_expire { get; set; }
        public string trade_type { get; set; }
        public string prepay_id { get; set; }
        public string transaction_id { get; set; }
        public string trade_state { get; set; }
        public Nullable<int> total_fee { get; set; }
        public string time_end { get; set; }
        public string payType { get; set; }
    }
}
