//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2BData
{
    using System;
    using System.Collections.Generic;
    
    public partial class skunew
    {
        public int ID { get; set; }
        public string skuId { get; set; }
        public string skuName { get; set; }
        public string logo { get; set; }
        public string status { get; set; }
        public string saleAttrs { get; set; }
        public Nullable<decimal> jdPrice { get; set; }
        public string outerId { get; set; }
        public string barCode { get; set; }
        public string supplier { get; set; }
        public string partermodel { get; set; }
        public Nullable<decimal> poprice { get; set; }
        public string pocurrency { get; set; }
        public string taxrate { get; set; }
        public string HScode { get; set; }
        public Nullable<int> iscrosspro { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
        public Nullable<System.DateTime> modifiedtime { get; set; }
        public string creater { get; set; }
        public string modified { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<decimal> price130 { get; set; }
        public Nullable<decimal> price105 { get; set; }
    }
}
