//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2BData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade
    {
        public string tid { get; set; }
        public string shippingtype { get; set; }
        public string buyermessage { get; set; }
        public string buyermemo { get; set; }
        public string sellermemo { get; set; }
        public string status { get; set; }
        public Nullable<decimal> discountfee { get; set; }
        public Nullable<decimal> adjustfee { get; set; }
        public Nullable<decimal> payment { get; set; }
        public Nullable<decimal> totalfee { get; set; }
        public Nullable<decimal> postfee { get; set; }
        public Nullable<decimal> receivedpayment { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public System.DateTime created { get; set; }
        public Nullable<System.DateTime> paytime { get; set; }
        public string alipaywarnmsg { get; set; }
        public string uid { get; set; }
        public string receivername { get; set; }
        public string receiverstate { get; set; }
        public string receivercity { get; set; }
        public string receiverdistrict { get; set; }
        public string receiveraddress { get; set; }
        public string receiverzip { get; set; }
        public string receivermobile { get; set; }
        public string receiverphone { get; set; }
        public Nullable<System.DateTime> consigntime { get; set; }
        public string buyeremail { get; set; }
        public int shopId { get; set; }
        public string selleralipayno { get; set; }
        public string sellermobile { get; set; }
        public string sellerphone { get; set; }
        public string sellername { get; set; }
        public string selleremail { get; set; }
        public string tradefrom { get; set; }
        public string sellernick { get; set; }
        public string buyernick { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<long> num { get; set; }
        public string alipayno { get; set; }
        public string snapshoturl { get; set; }
        public string snapshot { get; set; }
        public string tradememo { get; set; }
        public string buyeralipayno { get; set; }
        public string invoicename { get; set; }
        public string IDCard { get; set; }
        public string payNumber { get; set; }
        public string payType { get; set; }
    }
}
