//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2BData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeDetail
    {
        public long oid { get; set; }
        public string tid { get; set; }
        public Nullable<decimal> totalfee { get; set; }
        public Nullable<decimal> discountfee { get; set; }
        public Nullable<decimal> adjustfee { get; set; }
        public Nullable<decimal> payment { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string status { get; set; }
        public Nullable<long> refundid { get; set; }
        public long numiid { get; set; }
        public Nullable<long> skuid { get; set; }
        public long num { get; set; }
        public string title { get; set; }
        public Nullable<decimal> price { get; set; }
        public string refundstatus { get; set; }
        public string outeriid { get; set; }
        public string outerskuid { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public Nullable<System.DateTime> consigntime { get; set; }
        public string shippingtype { get; set; }
        public string logisticscompany { get; set; }
        public string invoiceno { get; set; }
    }
}
